version: "3.8"

services:
    catalogdb:
        image: mongo
        container_name: catalogdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    catalog.api:
        restart: always
        container_name: catalog.api
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        ports:
            - "8000:80"
volumes:
    mongo_data:
