version: "3.8"

services:
    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: microservices/Lotus.Catalog.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "80"
